package com.baseProject.myBaseProject.enums;

public enum RealtimeEventType {
    SESSION_CONNECTED,
    SESSION_RESUMPTION_UPDATED,
    USER_SPEECH_STARTED,
    USER_TRANSCRIPT_PARTIAL,
    USER_TRANSCRIPT_FINAL,
    ASSISTANT_SPEECH_STARTED,
    ASSISTANT_TRANSCRIPT_FINAL,
    ASSISTANT_INTERRUPTED,
    SESSION_DISCONNECTED,
    PROVIDER_ERROR
}
