package com.baseProject.myBaseProject.exception;

public enum ErrorCode {

    // ---- 404 ----
    AGENT_NOT_FOUND,
    ENDPOINT_NOT_FOUND,
    RESOURCE_NOT_FOUND,

    // ---- 409 ----
    DUPLICATE_EMAIL,
    DUPLICATE_REGISTRATION,
    INVALID_EVENT_STATE,
    EVENT_FULL,
    EVENT_ALREADY_STARTED,
    REGISTRATION_ALREADY_CANCELLED,
    CAPACITY_BELOW_ACTIVE_REGISTRATIONS,
    DATA_CONSTRAINT_VIOLATION,

    // ---- 400 ----
    VALIDATION_FAILED,
    MALFORMED_REQUEST,

    // ---- 401 / 403 ----
    INVALID_CREDENTIALS,
    AUTHENTICATION_REQUIRED,
    ACCOUNT_DISABLED,
    ACCESS_DENIED,

    // ---- 405 / 500 ----
    METHOD_NOT_ALLOWED,
    INTERNAL_ERROR
}
