package com.baseProject.myBaseProject.exception;

public enum ErrorCode {

    // ---- 404 ----
    AGENT_NOT_FOUND,
    ENDPOINT_NOT_FOUND,
    RESOURCE_NOT_FOUND,

    // ---- 409 ----
    DUPLICATE_EMAIL,
    DUPLICATE_REGISTRATION,
    INVALID_EVENT_STATE,
    EVENT_FULL,
    EVENT_ALREADY_STARTED,
    REGISTRATION_ALREADY_CANCELLED,
    CAPACITY_BELOW_ACTIVE_REGISTRATIONS,
    DATA_CONSTRAINT_VIOLATION,
    CV_ALREADY_PARSED,

    // ---- 400 ----
    VALIDATION_FAILED,
    MALFORMED_REQUEST,
    INVALID_CV_FILE,

    // ---- 401 / 403 ----
    INVALID_CREDENTIALS,
    AUTHENTICATION_REQUIRED,
    ACCOUNT_DISABLED,
    ACCESS_DENIED,
    INVALID_REFRESH_TOKEN,
    MISSING_REFRESH_TOKEN,
    INVALID_GOOGLE_TOKEN,

    // ---- 405 / 500 / 502 / 503 ----
    METHOD_NOT_ALLOWED,
    INTERNAL_ERROR,
    CV_STORAGE_FAILED,
    CV_PARSE_FAILED,
    GOOGLE_LOGIN_NOT_CONFIGURED,
    CV_PARSE_NOT_CONFIGURED
}
